source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
install! 'cocoapods',
:disable_input_output_paths => true,
:generate_multiple_pod_projects => true

target 'ClangTrace' do
  pod 'ClangTrace', :path => '../'

  target 'ClangTrace_Tests' do
    inherit! :search_paths

  end
end
